spring.application.name=userexpensechatbot
server.port=8084
spring.datasource.url=jdbc:postgresql://db.ennlyfmmmaptzecdcewl.supabase.co:5432/postgres?user=postgres&password=ExpenseTracker@1234
spring.datasource.username=guptaayushman24
spring.datasource.password=FinanceTracker@1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.ai.openai.api-key=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