version: "3.7"

services:
  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    command: >
      gcloud beta emulators pubsub start
      --host-port=0.0.0.0:8085
      --project=local-project
    ports:
      - "8085:8085"

  pubsub-init:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    environment:
      PUBSUB_EMULATOR_HOST: pubsub-emulator:8085
    entrypoint: >
      bash -c "
        sleep 3 &&
        curl -s -X PUT http://pubsub-emulator:8085/v1/projects/local-project/topics/t-user-details &&
        curl -s -X PUT http://pubsub-emulator:8085/v1/projects/local-project/topics/t-user-expense-details &&
        echo 'Topics created'
      "
    depends_on:
      - pubsub-emulator

  redis:
    image: redis
    container_name: redis-userexpense
    ports:
      - "6379:6379"