spring.application.name=emailservice
server.port=8082

# ── Kafka Consumer (Confluent Cloud) ──
spring.kafka.bootstrap-servers=${CONFLUENT_BOOTSTRAP_SERVER}
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${CONFLUENT_API_KEY}" password="${CONFLUENT_API_SECRET}";
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=email-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# ── Mail (Mailtrap) ──
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=48a44ae1345d8e
spring.mail.password=0cf4fcd0a4dd52

# ── Logging ──
logging.level.com.example=INFO
