spring.application.name=emailservice

# ── Kafka Consumer (Railway internal) ──
spring.kafka.bootstrap-servers=kafka-broker.railway.internal:9092
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# ── Mail ──
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=48a44ae1345d8e
spring.mail.password=0cf4fcd0a4dd52

# ── Logging ──
logging.level.com.example=INFO