spring.application.name=expensechatbot
jwt.secretKey=7z8eHnQqTz6gVw3p5kF3O0v1bE1s7l9iHj2aC7jN8A8=
# Ollama LLM configuration
ollama.base-url=http://localhost:11434
ollama.model-name=qwen2.5:7b
server.port=8084
# Database connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/financetrackeraipostgress
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate settings (optional but recommended for development)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
debug=true