# Database (MySQL - Filess.io)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.url=${MY_SQL_CONNECTION_STRING}
spring.datasource.username=${MY_SQL_USERNAME}
spring.datasource.password=${MY_SQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1

# Database (PostgreSQL - Aiven)
spring.datasource.secondary.url=${POSTGRESQL_CONNECTION_STRING}
spring.datasource.secondary.username=${POSTFRESQL_USERNAME}
spring.datasource.secondary.password=${POSTGRESQL_PASSWORD}
spring.datasource.secondary.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
jwt.secretKey=7z8eHnQqTz6gVw3p5kF3O0v1bE1s7l9iHj2aC7jN8A8=
spring.security.user.name=root
spring.security.user.password=root

# Redis (Upstash)
spring.redis.host=smooth-fawn-43048.upstash.io
spring.redis.port=6379
spring.redis.password=${REDIS_PASSWORD}
spring.redis.ssl.enabled=true
spring.redis.timeout=120s

# Mail
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=48a44ae1345d8e
spring.mail.password=0cf4fcd0a4dd52

# Gemini AI
spring.ai.vertex.ai.gemini.project-id=${GCP_PROJECT_ID}
spring.ai.vertex.ai.gemini.location=us-central1
spring.ai.vertex.ai.gemini.chat.options.model=gemini-1.5-flash

# GCP Pub/Sub
spring.cloud.gcp.project-id=${GCP_PROJECT_ID}

# CORS
app.cors.front-end-url=https://finance-tracker-frontend-virid.vercel.app

# Logging
logging.level.com.example=INFO
