spring.config.import=optional:file:.env[.properties]
spring.application.name=userexpense
server.port=8081

# MySQL DataSource
spring.datasource.mysql.jdbc-url=jdbc:mysql://localhost:3306/financetrackerai
spring.datasource.mysql.username=root
spring.datasource.mysql.password=root
spring.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver

# PostgreSQL DataSource
spring.datasource.postgres.jdbc-url=jdbc:postgresql://localhost:5432/financetrackeraipostgress
spring.datasource.postgres.username=postgres
spring.datasource.postgres.password=postgres
spring.datasource.postgres.driver-class-name=org.postgresql.Driver

spring.security.user.name=root
spring.security.user.password=root
jwt.secretKey=7z8eHnQqTz6gVw3p5kF3O0v1bE1s7l9iHj2aC7jN8A8=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
app.cors.front-end-url=http://localhost:5173
spring.jackson.serialization.write-dates-as-timestamps=false
spring.ai.openai.api-key=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
#Reddis Configuration
# Basic Connection
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=yourPassword
spring.redis.database=0
spring.redis.timeout=120s

# Lettuce specific pooling options
spring.redis.lettuce.pool.max-active=50
spring.redis.lettuce.pool.max-idle=50
spring.redis.lettuce.pool.min-idle=5
spring.redis.lettuce.pool.max-wait=5000ms

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=48a44ae1345d8e
spring.mail.password=0cf4fcd0a4dd52
